#!/usr/bin/env python3
"""
gen_keycodes.py -- build-time generator for keycodes_generated.hpp.

Puppetry's config files (macros.json) store combos as key/button NAMES
("KEY_LEFTCTRL", "BTN_LEFT", "KEY_F13", ...), same as the old Python
daemon did via evdev.ecodes. C++ has no equivalent of Python's runtime
"getattr(e, name)"/reverse-dict introspection over the evdev module, so
this script parses the system's own linux/input-event-codes.h (the same
header the kernel and every evdev binding are ultimately generated from)
and emits a static name<->code table as a C++ header.

Run at build time (via CMake) rather than committing a static table, so
it always matches whatever kernel headers the build environment actually
has -- new key codes added upstream need no changes here.

Usage: gen_keycodes.py <input-event-codes.h path> <output .hpp path>
"""
import re
import sys

DEFINE_RE = re.compile(r"^\s*#define\s+(KEY_[A-Za-z0-9_]+|BTN_[A-Za-z0-9_]+)\s+(\S+)")


def parse_defines(path):
    """Returns [(name, value_expr), ...] in file order, skipping pure
    aliases we can't resolve as a simple integer/hex literal at this
    stage (aliases like `#define KEY_MIN_INTERESTING KEY_MUTE` are
    resolved in a second pass below, since they reference a name that
    may appear earlier in the same file)."""
    out = []
    with open(path, "r") as f:
        for line in f:
            m = DEFINE_RE.match(line)
            if not m:
                continue
            name, expr = m.group(1), m.group(2).strip()
            # Strip trailing comments like "/* ... */"
            expr = re.sub(r"/\*.*?\*/", "", expr).strip()
            if not expr:
                continue
            out.append((name, expr))
    return out


def resolve(defines):
    """Resolves each (name, expr) to an int, where expr is either a
    literal (decimal/hex) or a reference to an earlier-defined name.
    Names that can't be resolved (function-like macros, expressions
    with operators we don't handle) are skipped -- Puppetry only ever
    needs simple KEY_*/BTN_* -> integer mappings, not the handful of
    macro-function entries in the header."""
    resolved = {}
    for name, expr in defines:
        if name in resolved:
            continue
        value = None
        if re.fullmatch(r"0[xX][0-9a-fA-F]+", expr):
            value = int(expr, 16)
        elif re.fullmatch(r"-?\d+", expr):
            value = int(expr)
        elif expr in resolved:
            value = resolved[expr]
        # else: something we don't understand (e.g. "(KEY_A+1)") -- skip it.
        if value is not None:
            resolved[name] = value
    return resolved


def main():
    if len(sys.argv) != 3:
        print("usage: gen_keycodes.py <input-event-codes.h> <output.hpp>", file=sys.stderr)
        sys.exit(1)
    in_path, out_path = sys.argv[1], sys.argv[2]

    defines = parse_defines(in_path)
    resolved = resolve(defines)

    if len(resolved) < 100:
        print(f"warning: only resolved {len(resolved)} KEY_/BTN_ defines from "
              f"{in_path} -- header format may have changed", file=sys.stderr)

    lines = []
    lines.append("// AUTO-GENERATED by tools/gen_keycodes.py -- do not edit by hand.")
    lines.append(f"// Source: {in_path}")
    lines.append("#pragma once")
    lines.append("#include <unordered_map>")
    lines.append("#include <string>")
    lines.append("#include <vector>")
    lines.append("#include <utility>")
    lines.append("")
    lines.append("namespace puppetry {")
    lines.append("")
    lines.append("// name -> code, for every KEY_*/BTN_* this build's kernel headers declare.")
    lines.append("inline const std::unordered_map<std::string, int>& key_name_to_code() {")
    lines.append("    static const std::unordered_map<std::string, int> table = {")
    for name, value in sorted(resolved.items(), key=lambda kv: kv[1]):
        lines.append(f'        {{"{name}", {value}}},')
    lines.append("    };")
    lines.append("    return table;")
    lines.append("}")
    lines.append("")
    lines.append("// code -> canonical name (first name seen for that code, KEY_ before BTN_,")
    lines.append("// shortest name wins ties) -- used for /aliases.json and error messages.")
    lines.append("inline const std::unordered_map<int, std::string>& key_code_to_name() {")
    lines.append("    static const std::unordered_map<int, std::string> table = [] {")
    lines.append("        std::unordered_map<int, std::string> m;")
    lines.append("        for (const auto& [name, code] : key_name_to_code()) {")
    lines.append("            auto it = m.find(code);")
    lines.append("            if (it == m.end() || name.size() < it->second.size()) {")
    lines.append("                m[code] = name;")
    lines.append("            }")
    lines.append("        }")
    lines.append("        return m;")
    lines.append("    }();")
    lines.append("    return table;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace puppetry")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"gen_keycodes.py: wrote {len(resolved)} key codes to {out_path}")


if __name__ == "__main__":
    main()
